import Head from "next/head"
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react"
import { Auth, ThemeSupa } from "@supabase/auth-ui-react"
import AcDetails from "../comp/AcDetails"

const HomePage = () => {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{!session ? <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" /> : <AcDetails session={session} />}</div>
    </>
  )
}

export default HomePage
