import Head from "next/head"
import { useSupabaseClient, useSession } from "@supabase/auth-helpers-react"
import { Auth, ThemeSupa } from "@supabase/auth-ui-react"
import AcDetails from "@/comp/AcDetails"

const HomePage = () => {
  const supabase = useSupabaseClient()
  const session = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>{session ? <AcDetails session={session} /> : <Auth supabaseClient={supabase} appearance={{ theme: ThemeSupa }} theme="dark" />}</div>
    </>
  )
}

export default HomePage
